---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Pagina's
- type: document
  path: content/homepage.md
  label: Home Page
- type: document
  path: content/over.md
  label: Over
- type: document
  path: content/aanbod.md
  label: Aanbod
- type: document
  path: content/contact.md
  label: Contact
- type: heading
  label: Projecten
- type: directory
  path: content/projects/tuinen
  label: Tuinen
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: content/projects/landgoederen
  label: Landgoederen
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: content/projects/openbaar
  label: Openbare Ruimte
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: content/projects/kunst
  label: Kunst
  create: documents
  match: "**/*"
  templates:
  - project
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
