---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: Project Titel
- type: textarea
  name: subtitle
  label: Project Omschrijving
- type: file
  name: image
  label: Project Afbeelding
