---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: Project Titel
- type: textarea
  name: subtitle
  label: Project Omschrijving
  config:
    max: 600
    min: 200
- name: pictures
  type: image_gallery
  config: {}
  label: Afbeeldingen
pages:
- content/projects/tuinen/een-renovatietuin-in-diepenveen.md
- content/projects/tuinen/een-tuin-in-de-stenen-kamer-in-deventer.md
- content/projects/tuinen/grote-tuin-in-een-woonwijk.md
