---
label: Project
hide_body: true
fields:
- type: text
  name: type
  label: type
- type: text
  name: title
  label: title
- type: textarea
  name: subtitle
  label: subtitle
- type: file
  name: image
  label: image
